apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-svc
  namespace: fadime-konuk-dev
spec:
  ports:
  - name: todo-svc
    port: 3000
    targetPort: 3000
  selector:
    app: todo-app
  